# Playbook to call multiple roles to configure systems
- name: Configure systems
  hosts: 13.233.158.8
  become: yes

  tasks:

- name: Call Roles
  hosts: 13.233.158.8
  roles:
   #- hostname
   #- firewalld
   #- ntp-config
   - motd
